# Import all models so SQLAlchemy relationships are registered
from app.models.role import VaiTro
from app.models.user_status import TrangThaiNguoiDung
from app.models.user import User
from app.models.profile import Profile
from app.models.user_settings import UserSettings
from app.models.language import Language
from app.models.category import Category
from app.models.object import Object
from app.models.example import ViDu
from app.models.translation import Translation
from app.models.object_media import ObjectMedia
from app.models.learning_progress import LearningProgress
from app.models.review_log import ReviewLog
from app.models.user_collection import UserCollection
from app.models.collection_item import CollectionItem
from app.models.scan_history import ScanHistory
from app.models.ai_feedback_report import AIPrediction
from app.models.dictionary_lookup import DictionaryLookup
