"""add missing timestamps and required fields to all models

Revision ID: d700d2ce6f5f
Revises: b7f10a17d61f
Create Date: 2026-03-11 09:44:34.631197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd700d2ce6f5f'
down_revision: Union[str, Sequence[str], None] = 'b7f10a17d61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_feedback_reports', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('collection_items', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('collection_items', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('collection_items', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint('unique_collection_item', 'collection_items', ['collection_id', 'translation_id'])
    op.add_column('data_versions', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('data_versions', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('data_versions', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'data_versions', ['table_name'])
    op.add_column('languages', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('languages', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('learning_progress', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('learning_progress', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('object_media', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('object_media', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('objects', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('objects', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('profiles', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('scan_history', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('scan_history', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('translations', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('translations', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_collections', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_settings', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_settings', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'updated_at')
    op.drop_column('user_settings', 'created_at')
    op.drop_column('user_collections', 'updated_at')
    op.drop_column('translations', 'updated_at')
    op.drop_column('translations', 'created_at')
    op.drop_column('scan_history', 'updated_at')
    op.drop_column('scan_history', 'created_at')
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'created_at')
    op.drop_column('objects', 'updated_at')
    op.drop_column('objects', 'created_at')
    op.drop_column('object_media', 'updated_at')
    op.drop_column('object_media', 'created_at')
    op.drop_column('learning_progress', 'updated_at')
    op.drop_column('learning_progress', 'created_at')
    op.drop_column('languages', 'updated_at')
    op.drop_column('languages', 'created_at')
    op.drop_constraint(None, 'data_versions', type_='unique')
    op.drop_column('data_versions', 'updated_at')
    op.drop_column('data_versions', 'created_at')
    op.drop_column('data_versions', 'id')
    op.drop_constraint('unique_collection_item', 'collection_items', type_='unique')
    op.drop_column('collection_items', 'updated_at')
    op.drop_column('collection_items', 'created_at')
    op.drop_column('collection_items', 'id')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('ai_feedback_reports', 'updated_at')
    # ### end Alembic commands ###
